### PR TITLE
fix pom

### PR DESCRIPTION
**Pull request by AndyWu2015**
hey Koen , I find it would be better to change the version of portal-kernel and add one more dependency for the compiling error.

### CODE REVIEW

**Comment by KoenOlaerts** [comment]
Hi Andy,

Thanks for the input. 

Could you please elaborate on why you find it better to change the version of portal-kernel? It seems like a downgrade to me (current version is already 2.16.0).
Also could you provide info on why you would add DDM as a dependency? There is no direct requirement from the code for this.

Andy, what compiling error are you getting? Currently I have none, even when I change the portal-kernel version according to your proposal.

**Comment by AndyWu2015** [comment]
I import the project in to eclipse and get 
`The type com.liferay.dynamic.data.mapping.storage.DDMFormValues cannot be resolved. It is indirectly referenced from required .class files`
on SimpleEditDisplayContext.java file

then , I add com.liferay.dynamic.data.mapping.api dependency and it compiles well.
but when I deploy to liferay portal 7 ga3 , it will say "Unresolved requirement: Import-Package: com.liferay.portal.kernel.util; version="[7.6.0,8.0.0)""

then I change the portal-kernel version to 2.0.0 and it works

**Comment by KoenOlaerts** [comment]
Hello Andy,

I'm sorry to say but I don't receive that compilation error in Intellij. Even packaging the module via the command line poses no problem (not even after deleting my entire local maven repo). Now the DDM artifact isn't part of my local repository so I still believe there is no dependency for it.

So I believe this is rather an IDE issue. Thus it should not be solved via the code.

**Comment by AndyWu2015** [comment]
okay, got it , thanks for you report. close this.

**Pull request closed without merging**
